var data = [{
  'name': 'Capacidades especiales',
  'image': '../assets/images/posts/1.jpg',
  'description': 'Las personas con “capacidades diferentes” no son personas enfermas a las que hay que compadecer y sobreproteger.',
  'type': 'popular',
  'user': '../assets/images/users-post/user1.jpeg',
  'contact': 'Maria Flores',
  'info':'https://www.hola.com/ninos/2015070779801/pablo-pineda-entrevista/'
},
{
  'name': '¿Un hijo diferente?',
  'image': '../assets/images/posts/2.jpg',
  'description': 'Pablo Pineda: Yo les diría que reacciones como el miedo o la incertidumbre ante el futuro son normales pero hay que darles la vuelta y pensar que es un reto para ellos y que por tanto hay que intentarlo y no pensar tanto en el futuro.',
  'type': 'popular',
  'user': '../assets/images/users-post/user2.jpg',
  'contact': 'Mayra Alvarez',
  'info':'https://www.hola.com/ninos/2015070779801/pablo-pineda-entrevista/'
},
{
  'name': 'Clasificación',
  'image': '../assets/images/posts/3.jpg',
  'description': 'Discapacidad física, sensorial, intelectual, psíquica: ',
  'type': ' popular',
  'user': '../assets/images/users-post/user3.jpg',
  'contact': 'Patricia León',
  'info':'http://www.monografias.com/trabajos93/ninos-habilidades-especiales/ninos-habilidades-especiales.shtml'
},
{
  'name': 'Programas',
  'image': '../assets/images/posts/4.jpg',
  'description': 'El trabajo realizado por niños y adolescentes del programa musical Orquestando fue reconocido por el Congreso de la República por mejorar la calidad de vida de las personas con Síndrome de Dawn, entre otras habilidades especiales.',
  'type': 'comentado',
  'user': '../assets/images/users-post/user4.jpeg',
  'contact': 'Jennifer Urrutia',
  'info': 'https://elcomercio.pe/lima/reconocen-programa-sinfonia-inclusiva-ninos-habilidades-especiales-424649',
},
{
  'name': 'Situación actual',
  'image': '../assets/images/posts/5.jpg',
  'description': 'El Ministerio de Educación (Minedu) informó hoy que potencialmente existen unos 600 mil niños con habilidades diferentes en todo el Perú, de los cuales, la gran mayoría, posee retardo mental y discapacidades intelectuales.',
  'type': 'comentado',
  'user': '../assets/images/users-post/user5.jpg',
  'contact': 'Astrid Martínez',
  'info': 'https://www.humanium.org/es/ninos-discapacitados/',
},
{
  'name': 'Educación',
  'image': '../assets/images/posts/6.jpg',
  'description': 'Los niños con habilidades diferentes tienen derecho a la educación. Por ello, existe una carrera que forma los profesionales idóneos para tal fin: Educación Especial. Seguirla implica poseer una serie de habilidades particulares.',
  'type': 'comentado',
  'user': '../assets/images/users-post/user6.jpg',
  'contact': 'Rosa Serpa',
  'info': 'https://www.guiainfantil.com/blog/salud/sindrome-de-down/ninos-con-discapacidad-o-ninos-con-capacidades-diferentes/',
},
{
  'name': 'Autismo: causas',
  'image': '../assets/images/posts/7.jpg',
  'description': 'Los expertos aún no están seguros de todas las causas del autismo. Lo más seguro es que haya causas múltiples en vez de sólo una. Parece ser que un número de circunstancias diversas, que incluyen factores ambientales, biológicos y genéticos, sientan las bases para el autismo y hacen que un niño/a sea más propenso a padecer el trastorno.',
  'type': 'mas-visto',
  'user': '../assets/images/users-post/user8.jpg',
  'contact': 'Jessica Pérez',
  'info': 'https://www.vanguardia.com.mx/articulo/como-ayudar-los-ninos-con-capacidades-diferentes-o-problemas-de-aprendizaje/',
},
{
  'name': 'Niños y retos',
  'image': '../assets/images/posts/8.jpg',
  'description': 'Se estima que más del 15 por ciento de la población mundial tiene alguna condición que es considerada “especial”, como problemas cognitivos o trastornos de aprendizaje, factores que intervienen en su desarrollo integral.',
  'type': 'mas-visto',
  'user': '../assets/images/users-post/user9.jpeg',
  'contact': 'Raquel Gonzáles',
  'info': 'http://www.prensalibre.com/vida/salud-y-familia/los-retos-de-los-nios-con-capacidades-diferentes',
},
{
  'name': '¿Cómo ayudar?',
  'image': '../assets/images/posts/9.jpg',
  'description': 'Por experiencia propia, sé que el hecho de recibir la noticia de que tu hijo no es como los otros pequeños, sino que tendrá que lidiar de por vida con algunas dificultades para leer, escribir, comprender textos o gestos; hablar, hacer cuentas y relacionarse con sus compañeros, es difícil de comprender y asumir, y en no pocas ocasiones puede resultar devastadora.',
  'type': 'mas-visto',
  'user': '../assets/images/users-post/user10.jpg',
  'contact': 'Victoria Rivas',
  'info': 'http://www.mychildwithoutlimits.org/understand/autism/what-causes-autism/?lang=es',
},
];