var data = [{
  'name': 'Autismo',
  'image': '../assets/images/posts/1.jpg',
  'description': 'pequeña description',
  'type': 'popular',
  'user': '../assets/images/users-post/user1.jpg',
},
{
  'name': 'Indigo',
  'image': '../assets/images/posts/2.jpg',
  'description': 'pequeña description',
  'type': 'comentado',
  'user': '../assets/images/users-post/user1.jpg',
},
{
  'name': 'bebé3',
  'image': '../assets/images/posts/3.jpg',
  'description': 'pequeña description',
  'type': 'reciente',
  'user': '../assets/images/users-post/user1.jpg',
},
{
  'name': 'bebé4',
  'image': '../assets/images/posts/4.jpg',
  'description': 'Jr. Bambues 198, La Molina, Lima 15024, Perú',
  'type': 'popular',
  'user': '../assets/images/users-post/user1.jpg',
},
{
  'name': 'bebé5',
  'image': '../assets/images/posts/5.jpg',
  'description': 'Jr. Bambues 198, La Molina, Lima 15024, Perú',
  'type': 'comentado',
  'user': '../assets/images/users-post/user1.jpg',
},
{
  'name': 'bebé3',
  'image': '../assets/images/posts/3.jpg',
  'description': 'Jr. Bambues 198, La Molina, Lima 15024, Perú',
  'type': 'reciente',
  'user': '../assets/images/users-post/user1.jpg',
},
];